# To use:
#   $ conda env create -f environment.yml
#   $ conda activate <name>
name: machinelearnear-detectron2-sahi
dependencies:
  - python=3.8
  - pip
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - gh
  - opencv
  - pip:
    - git+https://github.com/obss/sahi.git
    - git+https://github.com/openai/CLIP.git
    - torch
    - torchvision
    - timm
    # - -r file:requirements.txt